project:
  output-dir: docs
  type: website

website:
  description: "A blog built with Quarto"
  site-url: site-url: https://meichen-kingsley.github.io/HDAT9800-Meichen-blog/ # you must change this appropriately for RSS feeds to work properly
  title: "HDAT9800-Meichen-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

